modLoader = "javafml"
loaderVersion = "[45,)"
license = "GNU LGPL v3"
# issueTrackerURL=""
[[mods]]
modId = "kthtech"
displayName = "KthTech"
version = "${file.jarVersion}"
displayTest = "MATCH_VERSION"
authors = "StableAgOH, Tiphereth-A"
description = '''KthTech'''
# updateJSONURL="" # https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
# displayURL=""
# logoFile="examplemod.png"
# credits="Thanks for this example mod goes to Java"

[[dependencies.kthtech]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.kthtech]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"
