name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Generate data
        id: data
        uses: gradle/gradle-build-action@v3
        with:
          arguments: runData --scan

      - name: Build
        id: build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build --scan

      - name: Add build scan URL as PR comment
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let body = '';
            if(${{ steps.data.outcome != 'success' }})
              body = '❌Generate data failed: ${{ steps.data.outputs.build-scan-url }}';
            else if(${{ steps.build.outcome != 'success' }})
              body = '❌Build failed: ${{ steps.build.outputs.build-scan-url }}';
            if(body) github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/
          if-no-files-found: error
